# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41f516733b392fdc80f4d5b06271e2d5"
name = "custom-price-first-app"
application_url = "https://creation-academics-stake-district.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "custom-checkout-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [
  "https://creation-academics-stake-district.trycloudflare.com/auth/callback",
  "https://creation-academics-stake-district.trycloudflare.com/auth/shopify/callback",
  "https://creation-academics-stake-district.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
